// Coop transport — thin client wrapper around the Cloudflare-Worker
// WebSocket relay. Owns connection lifecycle (host/join, reconnect,
// heartbeat), wraps app messages in the protocol envelope, and emits
// events on a `target` for the rest of the game to subscribe to.
//
// Events emitted (via EventTarget):
//   'open'      → CustomEvent({ roomId, you, host, peers })
//   'peer-in'   → CustomEvent({ peer })
//   'peer-out'  → CustomEvent({ peer, reason })
//   'host'      → CustomEvent({ host })
//   'msg'       → CustomEvent({ from, kind, body, to })
//   'close'     → CustomEvent({ code, reason })
//   'error'     → CustomEvent({ message })
//   'rtt'       → CustomEvent({ rtt })  — measured from server pings
//
// Reconnect policy: exponential backoff up to 30s, max 10 attempts,
// then surfaces a permanent close. Reconnect is preserved-credentials —
// peerId is regenerated by the server, so the room sees a peer-out then
// peer-in. Game logic should treat that as a brief "rejoin".

import { apiBase } from '../api_config.js';

const PROTOCOL_VERSION = 1;
const HEARTBEAT_INTERVAL_MS = 10_000;
const RECONNECT_BASE_MS = 800;
const RECONNECT_MAX_MS = 30_000;
const MAX_RECONNECTS = 10;

export class CoopTransport extends EventTarget {
  constructor() {
    super();
    this.ws = null;
    this.roomCode = null;
    this.peerName = 'anon';
    this.peerId = null;
    this.hostId = null;
    this.peers = new Map();   // peerId → { id, name }
    this._heartbeat = null;
    this._closing = false;
    this._reconnects = 0;
    this._reconnectT = null;
    this._lastPingTs = 0;
    this.rtt = null;
  }

  get isHost() { return this.peerId && this.peerId === this.hostId; }
  get isOpen() { return !!this.ws && this.ws.readyState === WebSocket.OPEN; }
  get peerCount() { return this.peers.size; }

  // Two-step host: POST /coop/host to mint a 6-char code, then call
  // join(code). Returning the code separately lets the caller surface
  // it for sharing before the WS handshake completes.
  async host(name) {
    if (name) this.peerName = name;
    const res = await fetch(`${apiBase()}/coop/host`, { method: 'POST' });
    if (!res.ok) throw new Error(`host failed: ${res.status}`);
    const { code } = await res.json();
    if (!code) throw new Error('no room code returned');
    await this.join(code, this.peerName);
    return code;
  }

  async join(code, name) {
    if (name) this.peerName = name;
    this.roomCode = code.toUpperCase();
    this._closing = false;
    this._reconnects = 0;
    return this._connect();
  }

  // Send an application-layer message. `to` null/undefined = broadcast
  // to all other peers. `kind` is a free-form tag the receiver routes
  // on (e.g. 'pos', 'input', 'snapshot', 'chat'). Body is any
  // JSON-serializable payload.
  send(kind, body, to = null) {
    if (!this.isOpen) return false;
    try {
      this.ws.send(JSON.stringify({
        v: PROTOCOL_VERSION, t: 'msg', kind, body, to,
      }));
      return true;
    } catch (_) {
      return false;
    }
  }

  close() {
    this._closing = true;
    if (this._reconnectT) clearTimeout(this._reconnectT);
    if (this._heartbeat) clearInterval(this._heartbeat);
    if (this.ws) {
      try { this.ws.close(); } catch (_) {}
    }
    this.ws = null;
    this.roomCode = null;
    this.peerId = null;
    this.hostId = null;
    this.peers.clear();
  }

  _connect() {
    if (!this.roomCode) return;
    const base = apiBase().replace(/^http/, 'ws');
    const url = `${base}/coop/ws/${this.roomCode}?name=${encodeURIComponent(this.peerName)}`;
    const ws = new WebSocket(url);
    this.ws = ws;

    ws.addEventListener('open', () => {
      // Server sends 'welcome' immediately after upgrade — we don't
      // need to do anything here besides start the keepalive loop.
      this._reconnects = 0;
      if (!this._heartbeat) {
        this._heartbeat = setInterval(() => this._pingTick(), HEARTBEAT_INTERVAL_MS);
      }
    });

    ws.addEventListener('message', (evt) => {
      let msg;
      try { msg = JSON.parse(evt.data); }
      catch (_) { return; }
      if (!msg || msg.v !== PROTOCOL_VERSION) return;
      this._handle(msg);
    });

    ws.addEventListener('close', (evt) => {
      this._dispatch('close', { code: evt.code, reason: evt.reason });
      if (this._heartbeat) { clearInterval(this._heartbeat); this._heartbeat = null; }
      this.ws = null;
      // Stale-state purge — server assigns a fresh peerId on
      // reconnect, so clearing here prevents a brief window where
      // application messages route against the OLD peerId between
      // close and the next welcome. peerCount reads also stay
      // consistent (no phantom peer-self).
      this.peerId = null;
      this.hostId = null;
      this.peers.clear();
      this.rtt = null;
      if (!this._closing && this._reconnects < MAX_RECONNECTS) {
        const delay = Math.min(RECONNECT_MAX_MS,
          RECONNECT_BASE_MS * Math.pow(1.7, this._reconnects));
        this._reconnects += 1;
        this._reconnectT = setTimeout(() => this._connect(), delay);
      }
    });

    ws.addEventListener('error', (e) => {
      this._dispatch('error', { message: 'socket error' });
    });
  }

  _handle(msg) {
    switch (msg.t) {
      case 'welcome': {
        this.peerId = msg.you;
        this.hostId = msg.host;
        this.peers.clear();
        for (const p of msg.peers || []) {
          this.peers.set(p.id, { id: p.id, name: p.name });
        }
        console.log('[coop] welcome',
          { roomId: msg.roomId, you: this.peerId, host: this.hostId,
            isHost: this.isHost, peerCount: this.peers.size });
        this._dispatch('open', {
          roomId: msg.roomId,
          you: this.peerId,
          host: this.hostId,
          peers: [...this.peers.values()],
        });
        return;
      }
      case 'peer-in': {
        if (msg.peer) this.peers.set(msg.peer.id, msg.peer);
        this._dispatch('peer-in', { peer: msg.peer });
        return;
      }
      case 'peer-out': {
        if (msg.peer) this.peers.delete(msg.peer.id);
        this._dispatch('peer-out', { peer: msg.peer, reason: msg.reason });
        return;
      }
      case 'host': {
        this.hostId = msg.host;
        this._dispatch('host', { host: msg.host });
        return;
      }
      case 'host-lost': {
        // Server killed the room because the host disconnected.
        // Per the architecture: we don't fake host-migration; the
        // remaining peer falls back to single-player. Stop the
        // reconnect loop so we don't dial right back into a dead
        // room, and dispatch close so the lobby can show a notice.
        console.warn('[coop] host-lost — run ended');
        this._closing = true;
        this._dispatch('host-lost', { message: msg.message || 'host disconnected' });
        try { this.ws?.close(); } catch (_) {}
        return;
      }
      case 'msg': {
        this._dispatch('msg', {
          from: msg.from, kind: msg.kind, body: msg.body, to: msg.to,
        });
        return;
      }
      case 'ping': {
        // Server-driven keepalive — echo back so the server knows
        // we're alive. Also lets us measure round-trip latency on
        // OUR own ping cycle below.
        try {
          this.ws.send(JSON.stringify({ v: PROTOCOL_VERSION, t: 'pong', ts: msg.ts }));
        } catch (_) {}
        return;
      }
      case 'pong': {
        if (this._lastPingTs && msg.ts === this._lastPingTs) {
          this.rtt = Date.now() - this._lastPingTs;
          this._dispatch('rtt', { rtt: this.rtt });
        }
        return;
      }
      case 'error':
        this._dispatch('error', { message: msg.message || msg.code });
        return;
    }
  }

  _pingTick() {
    if (!this.isOpen) return;
    this._lastPingTs = Date.now();
    try {
      this.ws.send(JSON.stringify({ v: PROTOCOL_VERSION, t: 'ping', ts: this._lastPingTs }));
    } catch (_) {}
  }

  _dispatch(name, detail) {
    this.dispatchEvent(new CustomEvent(name, { detail }));
  }
}

// Singleton — one transport per game tab. Subsequent host()/join()
// calls reset its internal state.
let _singleton = null;
export function getCoopTransport() {
  if (!_singleton) _singleton = new CoopTransport();
  return _singleton;
}
