-- Mission Control SQLite schema
-- Idempotent: every CREATE uses IF NOT EXISTS.
-- Migrations append blocks at the bottom — never rewrite existing tables.

-- ---------- core ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- The team's "what project are we working on right now" pointer.
INSERT OR IGNORE INTO meta (key, value) VALUES ('current_project', 'cold-exit');

-- ---------- tasks --------------------------------------------------------
-- Anything queued for any bot. Mirrors tools/local-ai.mjs runs but with
-- Discord origin tracking + status lifecycle.
CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,                       -- e.g. 'audit-shop-collisions'
  title TEXT NOT NULL,
  prompt TEXT NOT NULL,
  files_json TEXT,                          -- JSON array of file paths
  project TEXT NOT NULL DEFAULT 'cold-exit',
  owner TEXT NOT NULL,                      -- which bot ('wrenchy' / 'sage' / 'claudie' / ...)
  route_reason TEXT,                        -- why owner was picked
  status TEXT NOT NULL DEFAULT 'pending',   -- pending|in_progress|review|done|failed|blocked
  output_path TEXT,                         -- audits/<slug>.md
  output_summary TEXT,                      -- short post-run summary
  reviewer TEXT,                            -- next bot in handoff (nullable)
  origin_user_id TEXT,                      -- Discord user id who queued
  origin_channel_id TEXT,
  origin_message_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  started_at TEXT,
  finished_at TEXT,
  duration_ms INTEGER,
  error_text TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_owner ON tasks (owner);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks (project);

-- ---------- articles -----------------------------------------------------
-- Items Newsie scrapes from sources. One row per unique URL.
CREATE TABLE IF NOT EXISTS articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  source TEXT NOT NULL,                     -- 'hn' | 'reddit:LocalLLaMA' | 'rss:simonwillison.net' | 'github-trending'
  excerpt TEXT,                             -- first paragraph or HN tagline
  score INTEGER,                            -- source-side score (HN points, reddit upvotes)
  newsie_score INTEGER,                     -- 1-10 our internal relevance
  tags_json TEXT,                           -- JSON array, e.g. ["#ollama", "#ai-tools"]
  found_at TEXT NOT NULL DEFAULT (datetime('now')),
  posted_at TEXT,                           -- when Newsie posted to Discord
  message_id TEXT,                          -- Discord message id of the post
  status TEXT NOT NULL DEFAULT 'new'        -- new|posted|archived|spam
);
CREATE INDEX IF NOT EXISTS idx_articles_status ON articles (status);
CREATE INDEX IF NOT EXISTS idx_articles_source ON articles (source);
CREATE INDEX IF NOT EXISTS idx_articles_found_at ON articles (found_at);

-- ---------- ideas --------------------------------------------------------
-- Generated by Thinkie OR added manually. Tracks approval lifecycle.
CREATE TABLE IF NOT EXISTS ideas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  origin TEXT NOT NULL,                     -- 'thinkie' | 'user' | 'newsie' | 'sortie'
  source_article_id INTEGER,                -- nullable, FK to articles
  project TEXT,                             -- nullable, what project this targets
  category TEXT,                            -- 'tooling' | 'gameplay' | 'business' | 'ai-integration' | etc.
  decision TEXT NOT NULL DEFAULT 'pending', -- pending|approved|denied|later
  decision_at TEXT,
  decision_user_id TEXT,
  message_id TEXT,                          -- Discord message id where it was posted
  channel_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (source_article_id) REFERENCES articles(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_ideas_decision ON ideas (decision);
CREATE INDEX IF NOT EXISTS idx_ideas_project ON ideas (project);

-- ---------- sources ------------------------------------------------------
-- The watchlist Newsie scans. Editable at runtime — Newsie can suggest
-- new ones; user reacts to approve.
CREATE TABLE IF NOT EXISTS sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL,                       -- 'hn' | 'reddit' | 'rss' | 'github-trending'
  identifier TEXT NOT NULL,                 -- 'frontpage' | subreddit name | feed url | language
  label TEXT,                               -- human-friendly
  enabled INTEGER NOT NULL DEFAULT 1,
  added_at TEXT NOT NULL DEFAULT (datetime('now')),
  added_by TEXT,                            -- 'seed' | 'user' | 'newsie-suggested'
  approved_at TEXT,                         -- nullable: when user ✅'d
  UNIQUE (kind, identifier)
);

-- Seed the v1 source list. INSERT OR IGNORE so re-running is safe.
INSERT OR IGNORE INTO sources (kind, identifier, label, added_by, approved_at) VALUES
  ('hn',              'frontpage',         'Hacker News front page',     'seed', datetime('now')),
  ('reddit',          'LocalLLaMA',        'r/LocalLLaMA',               'seed', datetime('now')),
  ('reddit',          'MachineLearning',   'r/MachineLearning',          'seed', datetime('now')),
  ('reddit',          'singularity',       'r/singularity',              'seed', datetime('now')),
  ('reddit',          'programming',       'r/programming',              'seed', datetime('now')),
  ('reddit',          'cursor',            'r/cursor',                   'seed', datetime('now')),
  ('rss',             'https://simonwillison.net/atom/everything/', 'Simon Willison',             'seed', datetime('now')),
  ('rss',             'https://www.latent.space/feed', 'Latent Space',               'seed', datetime('now')),
  ('github-trending', 'javascript',        'GitHub trending — JS',       'seed', datetime('now')),
  ('github-trending', 'python',            'GitHub trending — Python',   'seed', datetime('now'));

-- ---------- watchlist ---------------------------------------------------
-- Topics Newsie scores articles against. Bootstrapped empty; grows from
-- user reactions over weeks (✅ on an article boosts its tags' weights).
CREATE TABLE IF NOT EXISTS watchlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic TEXT UNIQUE NOT NULL,
  weight REAL NOT NULL DEFAULT 1.0,
  hits INTEGER NOT NULL DEFAULT 0,          -- count of articles matched
  last_hit_at TEXT,
  added_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Bootstrap a few obvious watch topics. Newsie will add more as it sees
-- recurring matches.
INSERT OR IGNORE INTO watchlist (topic, weight) VALUES
  ('ollama', 1.5),
  ('local llm', 1.5),
  ('claude code', 1.3),
  ('cursor', 1.2),
  ('three.js', 1.4),
  ('webgl', 1.2),
  ('cloudflare', 1.1),
  ('discord bot', 1.1),
  ('roguelike', 1.4),
  ('extraction shooter', 1.4),
  ('indie game', 1.2),
  ('itch.io', 1.2),
  ('deepseek', 1.4),
  ('qwen', 1.4),
  ('agent framework', 1.3);

-- ---------- thoughts ---------------------------------------------------
-- Free-form dumps from #thoughts / #dreams / #ideas. Sortie watches and
-- categorizes. Memory consolidation reads these too.
CREATE TABLE IF NOT EXISTS thoughts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel TEXT NOT NULL,                    -- 'thoughts' | 'dreams' | 'ideas'
  user_id TEXT NOT NULL,
  message_id TEXT UNIQUE NOT NULL,
  body TEXT NOT NULL,
  tags_json TEXT,                           -- Sortie fills this in
  category TEXT,                            -- Sortie fills this in
  consolidated INTEGER NOT NULL DEFAULT 0,  -- 1 once memory consolidation has eaten it
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_thoughts_consolidated ON thoughts (consolidated);

-- ---------- memory -----------------------------------------------------
-- Long-term facts Claudie distills from daily activity. Read at start of
-- each interactive session so future-Claudie has context.
CREATE TABLE IF NOT EXISTS memory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT NOT NULL,                        -- short slug, e.g. 'user-prefers-tight-prose'
  body TEXT NOT NULL,
  category TEXT,                            -- 'user' | 'project' | 'preference' | 'reference'
  project TEXT,                             -- nullable
  source TEXT,                              -- 'consolidation' | 'manual' | 'sortie'
  weight REAL NOT NULL DEFAULT 1.0,         -- importance for retrieval ordering
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_used_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_memory_category ON memory (category);
CREATE INDEX IF NOT EXISTS idx_memory_project ON memory (project);

-- ---------- bot events ------------------------------------------------
-- Every bot action logged. Dashboard reads recent rows to render the
-- "just finished" feed. Cheap insert, never deleted.
CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bot TEXT NOT NULL,                        -- 'claudie' | 'newsie' | 'thinkie' | 'sortie' | 'wrenchy' | 'sage'
  kind TEXT NOT NULL,                       -- 'task_started' | 'task_done' | 'digest_posted' | 'idea_filed' | 'error'
  task_id INTEGER,                          -- nullable FK to tasks
  body TEXT,                                -- short description
  meta_json TEXT,                           -- arbitrary structured data
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events (created_at);
CREATE INDEX IF NOT EXISTS idx_events_bot ON events (bot);
