// Central store of live-tunable values. Modules read from this object each
// frame so the debug panel can mutate values without re-wiring anything.
export const tunables = {
  // Live lighting tunables — scene.js reads these when building the
  // scene, main.js's syncLighting() updates the live light refs each
  // frame so console edits take effect without a reload. Press F3
  // in-game to dump the current values to the browser console.
  lighting: {
    hemiSky:             0x4a1575,
    hemiGround:          0x1e1f25,
    hemiIntensity:       0.000,
    keyColor:            0xaec4d8,
    keyIntensity:        3.000,
    fillColor:           0x191a48,
    fillIntensity:       2.000,
    rimColor:            0xf358df,
    rimIntensity:        2.000,
    fogColor:            0x22252a,
    fogDensity:          0.0000,
    playerAuraColor:     0xffffff,
    playerAuraIntensity: 0.000,
    playerAuraDistance:  15.00,
    playerAuraDecay:     3.35,
  },
  move: {
    walkSpeed: 5,
    sprintSpeed: 10,
    crouchSpeed: 3,
    crouchSprintSpeed: 5.5,  // held crouch + sprint — faster than sneak, noisier
    accel: 50,
    friction: 20,
    standMuzzleY: 1.18,
    crouchMuzzleY: 0.78,
  },
  dash: {
    speed: 15,
    duration: 0.2,
    cooldown: 0.25,
    doubleTapWindow: 0.22,
    iFrames: 0.12,
  },
  roll: {
    speed: 15,
    duration: 0.45,
    cooldown: 0.75,
    iFrames: 0.3,
  },
  slide: {
    entrySpeedMin: 8,
    startBoost: 1.25,
    friction: 5,
    minDuration: 0.25,
    maxDuration: 1.2,
    steerStrength: 3,
  },
  jump: {
    impulse: 7.0,
    gravity: 22.0,
  },
  crouch: {
    heightScale: 0.55,
  },
  ads: {
    moveMultiplier: 0.55,
    enterTime: 0.28,
  },
  attack: {
    headMultiplier: 2.5,
    tracerLife: 0.07,
    muzzleFlashLife: 0.05,
    impactLife: 0.18,
  },
  zones: {
    head:  { damageMult: 2.5 },
    torso: { damageMult: 1.0 },
    legs:  { damageMult: 0.85, slowDuration: 2.0, slowFactor: 0.45 },
    arm:   { damageMult: 0.7,  disarmChance: 0.7 },
  },
  enemy: {
    maxHealth: 100,
    respawnDelay: 2.0,
    hitFlashTime: 0.08,
    knockback: 0.25,
  },
  player: {
    maxHealth: 100,
    regenDelay: 3.5,
    regenRate: 7,
    regenLossFactor: 0.5,   // fraction of each hit that locks out of natural regen
    hitFlashTime: 0.15,
    collisionRadius: 0.4,
  },
  status: {
    bleedDps: 3,            // current-HP DoT while bleeding
    brokenDps: 2,           // current-HP DoT while broken
    brokenCapDps: 1.2,      // regenCap DoT while broken (makes it urgent)
    bleedDuration: 12,      // seconds a bleed lasts untreated
    brokenDuration: 20,     // seconds a broken bone lasts untreated
    meleeBleedChance: 0.22, // chance a melee enemy swing inflicts bleed
    meleeBrokenChance: 0.10,// chance a melee swing cracks a bone
    bulletBleedChance: 0.08,// chance a bullet hit causes a bleed
  },
  stamina: {
    max: 100,
    regenRate: 35,
    regenDelay: 0.7,
    dodgeCost: 20,
    rollCost: 28,
    comboCosts: [5, 6, 14],     // per combo step index — halved from [10,12,28]
    blockDrainRate: 5,           // per second held
    deflectCost: 6,              // extra per absorbed projectile
    parryCost: 10,
    minToAct: 8,                 // below this, new actions are gated
  },
  block: {
    moveMultiplier: 0.4,
    parryWindow: 0.28,
    spinSpeed: 9,
    redirectDamageMult: 1.6,
    deflectFlashLife: 0.18,
  },
  ai: {
    active: true,
    spreadMultiplier: 2.2,     // makes AI aim noticeably worse than player
    flankChance: 0.55,
    maxHealth: 100,
    respawnDelay: 10.0,
    detectionRange: 18,          // ~one room; was 32 before the room-scale rework
    detectionAngleDeg: 140,
    // Point-blank "presence" bubble — LoS within this distance forces
    // detection regardless of cone, rear-blindspot, or stealth mult.
    // Keeps a crouched-in-shadow player from walking right up to an
    // enemy's face undetected.
    proximityRange: 3.0,
    loseTargetTime: 2.0,
    reactionTime: 0.35,
    preferredRange: 15,
    rangeTolerance: 2.5,
    maxFireRange: 50,          // longest distance AI will attempt a shot
    moveSpeed: 3.4,
    strafeSpeed: 2.2,          // sideways component when flanking
    collisionRadius: 0.45,
  },
  meleeEnemy: {
    maxHealth: 100,
    respawnDelay: 9.0,
    moveSpeed: 5.6,
    detectionRange: 14,          // ~one room; was 22 before room-scale rework
    proximityRange: 3.0,         // LoS within this distance forces detection regardless of stealth
    swingRange: 1.9,
    swingWindup: 0.22,
    swingDamage: 16,
    swingCooldown: 0.5,
    collisionRadius: 0.42,
    dashRange: 5.0,       // start a dash-close inside this distance
    dashSpeed: 11.0,      // boost speed while dashing
    dashDuration: 0.28,
    dashCooldown: 1.6,
  },
  melee: {
    // Player's F-swipe. Single melee weapon for now — per-weapon variants later.
    swipeRange: 2.6,
    swipeAngleDeg: 95,
    swipeDamage: 40,
    swipeCooldown: 0.35,
    swipeKnockback: 4.5,
    swipePenetration: 999,     // arc hits everything in cone by default
    swipeArcLife: 0.14,
  },
  procgen: {
    arenaSize: 44,
    fullWalls: 7,
    lowCovers: 10,
    gapWalls: 3,
    meleeEnemies: 5,
    rangedEnemies: 2,
  },
  loot: {
    pickupRadius: 2.2,
    bobAmplitude: 0.08,
  },
  camera: {
    viewHeight: 16,
    followLerp: 9,
  },
  xp: {
    level1Cost: 80,
    perLevel: 50,
    killValue: { gunman: 30, melee: 18 },
  },
  stealth: {
    crouchDetectionMult: 0.5,   // crouched player's effective detection distance
    crouchSprintDetectionMult: 0.88,  // sprinting while crouched — extra noise
    executeRange: 1.7,
    executeBackDot: -0.15,       // dot(enemy.forward, toPlayer) must be below this
  },
  currency: {
    // credits dropped per enemy kill, roll in [min, max] range.
    dropChance: 0.7,
    amounts: {
      normal:  [4, 12],
      subBoss: [35, 65],
      boss:    [110, 180],
    },
    sellMult: 0.35,
    // Shop prices, set so a rare/epic/legendary purchase is a real
    // commitment rather than a casual pickup. Roughly 5–10× the
    // pre-rebalance numbers; rare gear is intentionally a big spend.
    basePrice: {
      common:    1500,
      uncommon:  4500,
      rare:      12000,
      epic:      32000,
      legendary: 80000,
    },
    // Random ±% price fluctuation rolled when a merchant's stock is generated.
    priceFluxRange: 0.25,
    // Per-level shop price ramp — every level past 1 adds this to the
    // price multiplier. priceFor(item, shopMult) gets shopMult that
    // already includes this factor (computed in main.js via getShopMult).
    levelPriceRamp: 0.18,
  },
  healer: {
    smallHeal: 40,
    smallCost: 20,
    fullCost:  55,
  },
  merchant: {
    stockSize: 6,
  },
  rarity: {
    tiers: ['common', 'uncommon', 'rare', 'epic', 'legendary'],
    colors: {
      common:    0x8a8f99,
      uncommon:  0x4a9a5a,
      rare:      0x4a7ac9,
      epic:      0x9a5ac9,
      legendary: 0xd0a038,
    },
  },
  durability: {
    weaponDecayPerShot: 0.005,   // tiny — weapons effectively don't break
    weaponDecayPerSwipe: 0.02,
    armorDamageRatio: 0.55,      // fraction of incoming dmg routed to armor HP
    minRepairability: 0.85,      // doc'd here for the store later
  },
  burn: {
    // Burn now stacks per fire-damage instance — each stack contributes
    // `dps` per second, and the stack count decays when burnT hits 0.
    // Duration is the timer window per stack-refresh; longer exposure
    // = bigger stack = bigger total DoT.
    duration: 12.0,
    dps: 6,
  },
  medkit: {
    smallHeal: 30,
    largeHeal: 65,
  },
  weapons: [
    {
      name: 'pistol',
      type: 'ranged',
      class: 'pistol',
      rarity: 'common',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi',
      fireRate: 4.5,
      damage: 38,
      range: 38,
      hipSpread: 0.06,
      adsSpread: 0.005,
      adsZoom: 0.82,
      adsPeekDistance: 3.5,
      tracerColor: 0xffd27a,
      muzzleLength: 0.5,
      muzzleGirth: 0.12,
      pelletCount: 1,
      burstCount: 1,
      burstInterval: 0,
      magSize: 14,
      reloadTime: 0.8,
    },
    {
      name: 'smg',
      type: 'ranged',
      class: 'smg',
      rarity: 'common',
      attachmentSlots: ['muzzle', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto',
      fireRate: 14,
      damage: 15,
      range: 28,
      hipSpread: 0.17,
      adsSpread: 0.04,
      adsZoom: 0.75,
      adsPeekDistance: 4.5,
      tracerColor: 0xcfd2d8,
      muzzleLength: 0.7,
      muzzleGirth: 0.13,
      pelletCount: 1,
      burstCount: 1,
      burstInterval: 0,
      magSize: 32,
      reloadTime: 1.1,
    },
    {
      name: 'shotgun',
      type: 'ranged',
      class: 'shotgun',
      rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'underRail', 'topRail', 'stock', 'magazine'],
      fireMode: 'semi',
      fireRate: 1.3,
      damage: 13,
      range: 22,
      hipSpread: 0.22,
      adsSpread: 0.10,
      adsZoom: 0.85,
      adsPeekDistance: 3.0,
      tracerColor: 0xff7a3a,
      muzzleLength: 0.85,
      muzzleGirth: 0.17,
      pelletCount: 8,
      burstCount: 1,
      burstInterval: 0,
      magSize: 6,
      reloadTime: 1.6,
    },
    {
      name: 'rifle',
      type: 'ranged',
      class: 'rifle',
      rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'burst',
      fireRate: 2.3,
      damage: 26,
      range: 65,
      hipSpread: 0.10,
      adsSpread: 0.012,
      adsZoom: 0.55,
      adsPeekDistance: 8.0,
      tracerColor: 0x9dd0ff,
      muzzleLength: 0.95,
      muzzleGirth: 0.14,
      pelletCount: 1,
      burstCount: 3,
      burstInterval: 0.07,
      magSize: 30,
      reloadTime: 1.25,
    },
    {
      name: 'lmg',
      type: 'ranged',
      class: 'lmg',
      rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'magazine'],
      fireMode: 'auto',
      fireRate: 11,
      damage: 34,
      range: 50,
      hipSpread: 0.24,
      adsSpread: 0.072,
      adsZoom: 0.65,
      adsPeekDistance: 6.0,
      tracerColor: 0xffae5a,
      muzzleLength: 1.05,
      muzzleGirth: 0.16,
      pelletCount: 1,
      burstCount: 1,
      burstInterval: 0,
      magSize: 80,
      reloadTime: 2.25,
    },
    {
      name: 'flamethrower',
      type: 'ranged',
      // Reclassed under the unified 'exotic' mastery family (flame, GL,
      // RL, dart, flare). Gameplay-side flame behaviour (fire spread,
      // burn ticks) gates on `fireMode === 'flame'` so re-tagging the
      // class here is safe.
      class: 'exotic',
      rarity: 'rare',
      attachmentSlots: ['underRail', 'sideRail', 'magazine'],
      fireMode: 'flame',
      fireRate: 0,
      damage: 5,                  // per tick
      range: 6.5,
      hipSpread: 0,
      adsSpread: 0,
      adsZoom: 0.95,
      adsPeekDistance: 1.5,
      tracerColor: 0xff6020,
      muzzleLength: 0.95,
      muzzleGirth: 0.18,
      pelletCount: 1,
      burstCount: 1,
      burstInterval: 0,
      magSize: 100,
      reloadTime: 5.0,            // long swap-tank reload — flamer is a commit
      flameAngleDeg: 36,
      flameTickRate: 20,          // 5s of held fire before dry; was 12 (~8s)
      // Loudness — `alertEnemiesFromShot` reads `weapon.noiseRange` when
      // present. A roaring flame jet is plainly louder than a pistol;
      // wakes the whole next room.
      noiseRange: 36,
    },
    // --- Extended pistol lineup ---
    {
      name: 'Glock', type: 'ranged', class: 'pistol', rarity: 'common',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 5.0, damage: 32, range: 32,
      hipSpread: 0.07, adsSpread: 0.008,
      adsZoom: 0.82, adsPeekDistance: 3.2,
      tracerColor: 0xe0d080, muzzleLength: 0.48, muzzleGirth: 0.12,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 17, reloadTime: 0.75,
    },
    {
      name: 'Sig P320', type: 'ranged', class: 'pistol', rarity: 'common',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 4.8, damage: 36, range: 34,
      hipSpread: 0.058, adsSpread: 0.006,
      adsZoom: 0.8, adsPeekDistance: 3.5,
      tracerColor: 0xffd27a, muzzleLength: 0.5, muzzleGirth: 0.12,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 17, reloadTime: 0.75,
    },
    {
      name: 'Beretta 92', type: 'ranged', class: 'pistol', rarity: 'common',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 5.2, damage: 34, range: 33,
      hipSpread: 0.06, adsSpread: 0.007,
      adsZoom: 0.82, adsPeekDistance: 3.4,
      tracerColor: 0xc8c8c8, muzzleLength: 0.5, muzzleGirth: 0.12,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 15, reloadTime: 0.75,
    },
    // --- Extended SMG lineup ---
    {
      name: 'AKS-74U', type: 'ranged', class: 'smg', rarity: 'common',
      attachmentSlots: ['muzzle', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 13, damage: 16, range: 26,
      hipSpread: 0.14, adsSpread: 0.03,
      adsZoom: 0.75, adsPeekDistance: 4.4,
      tracerColor: 0xc0cbd8, muzzleLength: 0.7, muzzleGirth: 0.13,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.1,
    },
    {
      name: 'PDW', type: 'ranged', class: 'smg', rarity: 'common',
      attachmentSlots: ['muzzle', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 16, damage: 14, range: 28,
      hipSpread: 0.16, adsSpread: 0.035,
      adsZoom: 0.72, adsPeekDistance: 4.6,
      tracerColor: 0xdbe5f0, muzzleLength: 0.72, muzzleGirth: 0.13,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.15,
    },
    {
      name: 'P90', type: 'ranged', class: 'smg', rarity: 'rare',
      attachmentSlots: ['muzzle', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'magazine'],
      fireMode: 'auto', fireRate: 18, damage: 14, range: 24,
      hipSpread: 0.13, adsSpread: 0.028,
      adsZoom: 0.74, adsPeekDistance: 4.2,
      tracerColor: 0xeaf0d0, muzzleLength: 0.6, muzzleGirth: 0.15,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 50, reloadTime: 1.4,
    },
    // --- Extended rifle lineup ---
    {
      name: 'M4', type: 'ranged', class: 'rifle', rarity: 'common',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 12, damage: 24, range: 60,
      hipSpread: 0.09, adsSpread: 0.010,
      adsZoom: 0.6, adsPeekDistance: 7.2,
      tracerColor: 0xaec8ea, muzzleLength: 0.9, muzzleGirth: 0.14,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.15,
    },
    {
      name: 'AK47', type: 'ranged', class: 'rifle', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 9, damage: 32, range: 55,
      hipSpread: 0.13, adsSpread: 0.02,
      adsZoom: 0.58, adsPeekDistance: 7.0,
      tracerColor: 0xe08030, muzzleLength: 0.96, muzzleGirth: 0.15,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.4,
    },
    {
      name: 'AS VAL', type: 'ranged', class: 'rifle', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 10, damage: 28, range: 60,
      hipSpread: 0.11, adsSpread: 0.014,
      adsZoom: 0.56, adsPeekDistance: 7.4,
      tracerColor: 0xf0a050, muzzleLength: 0.88, muzzleGirth: 0.14,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.25,
    },
    {
      // 9×39 DMR sibling of the AS VAL — shares the integrally-
      // suppressed 9×39 FBX (they use the same platform IRL). Slower
      // fire rate, higher per-shot damage, tighter ADS spread, longer
      // range; semi-auto only so it reads as a marksman rifle vs. the
      // VAL's close-range auto role.
      name: 'VSS', type: 'ranged', class: 'rifle', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 4.2, damage: 52, range: 78,
      hipSpread: 0.09, adsSpread: 0.008,
      adsZoom: 0.48, adsPeekDistance: 9.2,
      tracerColor: 0xe8a060, muzzleLength: 0.98, muzzleGirth: 0.12,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 10, reloadTime: 1.5,
    },
    // --- Revolvers ---
    {
      name: 'Snub Revolver', type: 'ranged', class: 'pistol', rarity: 'common',
      attachmentSlots: ['sideRail', 'topRail', 'grip', 'trigger'],
      fireMode: 'semi', fireRate: 4.0, damage: 40, range: 28,
      hipSpread: 0.09, adsSpread: 0.012,
      adsZoom: 0.84, adsPeekDistance: 3.0,
      tracerColor: 0xd2b48c, muzzleLength: 0.32, muzzleGirth: 0.11,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 5, reloadTime: 1.4,
    },
    {
      name: 'Revolver', type: 'ranged', class: 'pistol', rarity: 'uncommon',
      attachmentSlots: ['sideRail', 'topRail', 'grip', 'trigger'],
      fireMode: 'semi', fireRate: 3.2, damage: 62, range: 38,
      hipSpread: 0.065, adsSpread: 0.006,
      adsZoom: 0.78, adsPeekDistance: 4.2,
      tracerColor: 0xdab380, muzzleLength: 0.6, muzzleGirth: 0.13,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 6, reloadTime: 1.6,
    },
    {
      name: 'Desert Eagle', type: 'ranged', class: 'pistol', rarity: 'rare',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 2.6, damage: 95, range: 42,
      hipSpread: 0.075, adsSpread: 0.005,
      adsZoom: 0.7, adsPeekDistance: 4.8,
      tracerColor: 0xffd060, muzzleLength: 0.72, muzzleGirth: 0.17,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 7, reloadTime: 1.25,
    },
    {
      name: 'M1911', type: 'ranged', class: 'pistol', rarity: 'common',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 4.2, damage: 52, range: 34,
      hipSpread: 0.068, adsSpread: 0.007,
      adsZoom: 0.8, adsPeekDistance: 3.4,
      tracerColor: 0xe8c878, muzzleLength: 0.55, muzzleGirth: 0.13,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 7, reloadTime: 0.95,
    },
    {
      name: 'Flare Gun', type: 'ranged', class: 'exotic', rarity: 'uncommon',
      attachmentSlots: ['sideRail', 'topRail', 'grip'],
      fireMode: 'semi', fireRate: 1.2, damage: 14, range: 26,
      hipSpread: 0.12, adsSpread: 0.03,
      adsZoom: 0.85, adsPeekDistance: 3.0,
      tracerColor: 0xff6030, muzzleLength: 0.55, muzzleGirth: 0.14,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 1, reloadTime: 1.8,
      igniteOnHit: true,      // flagged for combat.js — hooks into burn status
    },

    // --- Extended SMG lineup ---
    {
      name: 'MP7', type: 'ranged', class: 'smg', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'magazine'],
      fireMode: 'auto', fireRate: 15, damage: 13, range: 28,
      hipSpread: 0.12, adsSpread: 0.026,
      adsZoom: 0.74, adsPeekDistance: 4.5,
      tracerColor: 0xbde0ff, muzzleLength: 0.62, muzzleGirth: 0.12,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 40, reloadTime: 1.1,
    },

    // --- Marksman / bolt lineup (still class: rifle — rides the rifle mastery tree) ---
    {
      name: 'Remington 700', type: 'ranged', class: 'sniper', rarity: 'common',
      attachmentSlots: ['muzzle', 'barrel', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 3.2, damage: 52, range: 70,
      hipSpread: 0.12, adsSpread: 0.008,
      adsZoom: 0.5, adsPeekDistance: 8.0,
      tracerColor: 0xd8b890, muzzleLength: 1.1, muzzleGirth: 0.13,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 5, reloadTime: 2.0,
    },
    {
      name: 'Mosin', type: 'ranged', class: 'sniper', rarity: 'common',
      attachmentSlots: ['muzzle', 'topRail', 'stock', 'trigger'],
      fireMode: 'semi', fireRate: 1.2, damage: 85, range: 75,
      hipSpread: 0.14, adsSpread: 0.006,
      adsZoom: 0.42, adsPeekDistance: 8.6,
      tracerColor: 0xa8845a, muzzleLength: 1.3, muzzleGirth: 0.12,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 5, reloadTime: 3.2,
    },
    {
      name: 'SVD', type: 'ranged', class: 'sniper', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'semi', fireRate: 3.8, damage: 72, range: 80,
      hipSpread: 0.1, adsSpread: 0.005,
      adsZoom: 0.44, adsPeekDistance: 9.0,
      tracerColor: 0xe0a050, muzzleLength: 1.25, muzzleGirth: 0.13,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 10, reloadTime: 2.2,
    },
    {
      name: 'Cheytac Intervention', type: 'ranged', class: 'sniper', rarity: 'epic',
      attachmentSlots: ['muzzle', 'topRail', 'stock', 'trigger', 'underRail'],
      fireMode: 'semi', fireRate: 0.9, damage: 200, range: 100,
      hipSpread: 0.18, adsSpread: 0.004,
      adsZoom: 0.36, adsPeekDistance: 10.0,
      tracerColor: 0xffe030, muzzleLength: 1.6, muzzleGirth: 0.2,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 5, reloadTime: 3.8,
    },

    // --- Extended rifle lineup ---
    {
      name: 'M16', type: 'ranged', class: 'rifle', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 11, damage: 26, range: 58,
      hipSpread: 0.10, adsSpread: 0.012,
      adsZoom: 0.58, adsPeekDistance: 7.2,
      tracerColor: 0x90b0c8, muzzleLength: 0.92, muzzleGirth: 0.14,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.2,
    },
    {
      name: 'M16A4', type: 'ranged', class: 'rifle', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 9, damage: 38, range: 62,
      hipSpread: 0.11, adsSpread: 0.014,
      adsZoom: 0.55, adsPeekDistance: 7.6,
      tracerColor: 0xc8a86a, muzzleLength: 0.96, muzzleGirth: 0.15,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 20, reloadTime: 1.4,
    },
    {
      name: 'Tavor', type: 'ranged', class: 'rifle', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 11, damage: 26, range: 55,
      hipSpread: 0.11, adsSpread: 0.014,
      adsZoom: 0.58, adsPeekDistance: 7.0,
      tracerColor: 0xd88838, muzzleLength: 0.88, muzzleGirth: 0.14,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.25,
    },
    {
      // AK-pattern with ACOG — rarer, tighter spread, more damage.
      name: 'AK47 ACOG', type: 'ranged', class: 'rifle', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 9, damage: 36, range: 68,
      hipSpread: 0.11, adsSpread: 0.009,
      adsZoom: 0.5, adsPeekDistance: 8.2,
      tracerColor: 0xe09040, muzzleLength: 0.96, muzzleGirth: 0.15,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 30, reloadTime: 1.4,
    },
    {
      // Tricked-out M4: scope, drum mag, flashlight, foregrip baked into the base stats.
      name: 'M4 Block II', type: 'ranged', class: 'rifle', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip', 'trigger', 'magazine'],
      fireMode: 'auto', fireRate: 13, damage: 26, range: 64,
      hipSpread: 0.07, adsSpread: 0.007,
      adsZoom: 0.56, adsPeekDistance: 7.6,
      tracerColor: 0xb0caea, muzzleLength: 0.92, muzzleGirth: 0.14,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 60, reloadTime: 1.35,
    },

    // --- LMG lineup ---
    {
      name: 'M240', type: 'ranged', class: 'lmg', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip'],
      fireMode: 'auto', fireRate: 11, damage: 24, range: 55,
      hipSpread: 0.22, adsSpread: 0.030,
      adsZoom: 0.62, adsPeekDistance: 6.8,
      tracerColor: 0xf0c870, muzzleLength: 1.05, muzzleGirth: 0.16,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 100, reloadTime: 3.0,
    },
    {
      name: 'RPK', type: 'ranged', class: 'lmg', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'barrel', 'sideRail', 'topRail', 'stock', 'grip', 'magazine'],
      fireMode: 'auto', fireRate: 10, damage: 29, range: 58,
      hipSpread: 0.20, adsSpread: 0.027,
      adsZoom: 0.6, adsPeekDistance: 7.0,
      tracerColor: 0xea8030, muzzleLength: 1.08, muzzleGirth: 0.15,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 75, reloadTime: 2.6,
    },
    {
      name: 'PKM', type: 'ranged', class: 'lmg', rarity: 'rare',
      attachmentSlots: ['muzzle', 'barrel', 'underRail', 'sideRail', 'topRail', 'stock', 'grip'],
      fireMode: 'auto', fireRate: 10, damage: 36, range: 62,
      hipSpread: 0.23, adsSpread: 0.031,
      adsZoom: 0.58, adsPeekDistance: 7.2,
      tracerColor: 0xe85020, muzzleLength: 1.12, muzzleGirth: 0.17,
      pelletCount: 1, burstCount: 1, burstInterval: 0,
      magSize: 100, reloadTime: 3.2,
    },

    // --- Extended shotgun ---
    {
      name: 'AA-12', type: 'ranged', class: 'shotgun', rarity: 'uncommon',
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'stock', 'grip', 'magazine'],
      fireMode: 'semi', fireRate: 1.8, damage: 18, range: 16,
      hipSpread: 0.22, adsSpread: 0.10,
      adsZoom: 0.82, adsPeekDistance: 3.8,
      tracerColor: 0xc89060, muzzleLength: 0.82, muzzleGirth: 0.16,
      pelletCount: 8, burstCount: 1, burstInterval: 0,
      magSize: 8, reloadTime: 3.5,
    },
    {
      // Unique artifact — infinite ammo, headshots pop heads, crouch turns
      // the wielder effectively invisible to AI.
      name: "Jessica's Rage",
      type: 'ranged',
      class: 'pistol',
      rarity: 'legendary',
      artifact: true,
      infiniteAmmo: true,
      artifactPerks: ['phantomCrouch', 'popperHead'],
      attachmentSlots: ['muzzle', 'sideRail', 'topRail', 'grip', 'trigger'],
      fireMode: 'semi',
      fireRate: 3.2,
      damage: 125,
      range: 48,
      hipSpread: 0.028,
      adsSpread: 0.002,
      adsZoom: 0.62,
      adsPeekDistance: 6,
      tracerColor: 0xff2a2a,
      muzzleLength: 0.75,
      muzzleGirth: 0.16,
      pelletCount: 1,
      burstCount: 1,
      burstInterval: 0,
      magSize: 999,
      reloadTime: 0.01,
    },

    // --- MYTHIC-tier weapons -------------------------------------------
    // Dropped only by major bosses (see main.js rollMythicDrop). Each is
    // a "signature" weapon with a unique mechanical twist. Jessica's
    // Rage stays apex and is NOT in this pool.
    {
      name: 'Dragonbreath',
      type: 'ranged', class: 'shotgun', rarity: 'mythic',
      igniteOnHit: true,         // sets hit enemies on fire via burn DoT
      mythic: true,
      attachmentSlots: ['muzzle', 'barrel', 'sideRail', 'stock'],
      fireMode: 'semi',
      fireRate: 1.4,
      damage: 34,
      range: 22,
      hipSpread: 0.18,
      adsSpread: 0.10,
      adsZoom: 0.82,
      adsPeekDistance: 4.5,
      tracerColor: 0xff6020,
      muzzleLength: 0.78, muzzleGirth: 0.18,
      pelletCount: 9,
      burstCount: 1, burstInterval: 0,
      magSize: 6, reloadTime: 2.1,
    },
    {
      name: 'Hailstorm Minigun',
      type: 'ranged', class: 'lmg', rarity: 'mythic',
      mythic: true,
      attachmentSlots: ['muzzle', 'barrel', 'sideRail', 'topRail', 'magazine'],
      fireMode: 'auto',
      fireRate: 18,                // extreme RPS
      damage: 16,
      range: 38,
      hipSpread: 0.055, adsSpread: 0.022,
      adsZoom: 0.70, adsPeekDistance: 5,
      tracerColor: 0xffc96a,
      muzzleLength: 0.95, muzzleGirth: 0.22,
      pelletCount: 1,
      burstCount: 1, burstInterval: 0,
      magSize: 200, reloadTime: 4.5,
    },
    {
      name: 'Kingsmaker GL',
      type: 'ranged', class: 'shotgun', rarity: 'mythic',
      mythic: true,
      explosive: true,
      attachmentSlots: ['muzzle', 'sideRail', 'stock'],
      // Proper grenade launcher — arcing ballistic with impact + fuse
      // detonation. Hitscan damage is zero; all damage is AoE via
      // firePlayerProjectile → onProjectileExplode.
      fireMode: 'projectile',
      projectile: 'grenade',
      projectileSpeed: 26,        // muzzle velocity (lower = more arc)
      projectileGrav: 9.8,
      projectileFuse: 2.4,        // seconds before self-detonate
      projectileBounce: 0.35,     // bounces off walls / ground
      projectileRadius: 0.18,
      aoeRadius: 5.5,
      aoeDamage: 110,
      aoeShake: 0.65,
      fireRate: 0.9,
      damage: 0,
      range: 28,
      hipSpread: 0.01, adsSpread: 0.003,
      adsZoom: 0.68, adsPeekDistance: 6,
      tracerColor: 0xf0a840,
      muzzleLength: 0.65, muzzleGirth: 0.24,
      pelletCount: 1,
      burstCount: 1, burstInterval: 0,
      magSize: 4, reloadTime: 3.0,
    },
    {
      name: 'Widowmaker Rocket',
      type: 'ranged', class: 'lmg', rarity: 'mythic',
      mythic: true,
      explosive: true,
      attachmentSlots: ['muzzle', 'sideRail', 'stock', 'topRail'],
      // Shoulder-fired rocket — straight-line flight, detonates on
      // any contact. Bigger blast, slower fire-rate, small magazine.
      fireMode: 'projectile',
      projectile: 'rocket',
      projectileSpeed: 42,
      projectileGrav: 0,
      projectileFuse: 4.0,
      projectileBounce: 0,
      projectileRadius: 0.22,
      aoeRadius: 7.0,
      aoeDamage: 180,
      aoeShake: 0.9,
      fireRate: 0.6,
      damage: 0,
      range: 60,
      hipSpread: 0.005, adsSpread: 0.0,
      adsZoom: 0.72, adsPeekDistance: 6,
      tracerColor: 0xff6020,
      muzzleLength: 1.2, muzzleGirth: 0.28,
      pelletCount: 1,
      burstCount: 1, burstInterval: 0,
      magSize: 2, reloadTime: 3.8,
    },
    {
      name: 'Whisper Dart',
      type: 'ranged', class: 'pistol', rarity: 'mythic',
      mythic: true,
      sleepOnHit: true,           // consumed by melee_enemy/gunman applyHit
      suppressedByDefault: true,  // zero noise radius so stealth kits stay silent
      attachmentSlots: ['muzzle', 'sideRail', 'topRail'],
      fireMode: 'semi',
      fireRate: 1.6,
      damage: 22,
      range: 36,
      hipSpread: 0.03, adsSpread: 0.005,
      adsZoom: 0.6, adsPeekDistance: 6,
      tracerColor: 0x6acff0,
      muzzleLength: 0.6, muzzleGirth: 0.11,
      pelletCount: 1,
      burstCount: 1, burstInterval: 0,
      magSize: 8, reloadTime: 1.4,
    },
    {
      name: 'Stormbreaker',
      type: 'melee', class: 'melee', rarity: 'mythic',
      mythic: true,
      waveOnSwing: true,          // swing emits a damage wave (see tickMeleeSwipe)
      meleeThreshold: 3.0,
      tracerColor: 0xa0c4ff,
      muzzleLength: 1.05, muzzleGirth: 0.10,
      adsZoom: 0.85, adsPeekDistance: 2.6,
      combo: [
        { close: { damage: 38, range: 2.6, angleDeg: 110, advance: 0.6,
                   startup: 0.07, active: 0.11, recovery: 0.18, window: 0.34, knockback: 3.0 },
          far:   { damage: 48, range: 3.4, angleDeg: 70,  advance: 2.0,
                   startup: 0.09, active: 0.12, recovery: 0.20, window: 0.34, knockback: 3.4 } },
        { close: { damage: 46, range: 2.7, angleDeg: 115, advance: 0.7,
                   startup: 0.09, active: 0.12, recovery: 0.22, window: 0.36, knockback: 3.4 },
          far:   { damage: 58, range: 3.6, angleDeg: 75,  advance: 2.2,
                   startup: 0.10, active: 0.13, recovery: 0.24, window: 0.36, knockback: 3.8 } },
        { close: { damage: 82, range: 2.9, angleDeg: 150, advance: 0.5,
                   startup: 0.12, active: 0.15, recovery: 0.36, window: 0.14, knockback: 5.6 },
          far:   { damage: 98, range: 3.8, angleDeg: 82,  advance: 2.4,
                   startup: 0.13, active: 0.15, recovery: 0.38, window: 0.14, knockback: 6.0 } },
      ],
    },

    // Low-tier melee — common drops from basic enemies. Shorter range and
    // weaker combos than the katana; shared combo structure so the player
    // can still swing them.
    {
      name: 'Knife',
      type: 'melee', class: 'melee', rarity: 'common',
      meleeThreshold: 2.8,
      tracerColor: 0xc0c0c8,
      muzzleLength: 0.55, muzzleGirth: 0.05,
      adsZoom: 0.8, adsPeekDistance: 2.4,
      combo: [
        { close: { damage: 10, range: 1.8, angleDeg: 90,  advance: 0.5,
                   startup: 0.04, active: 0.07, recovery: 0.14, window: 0.32, knockback: 1.2 },
          far:   { damage: 14, range: 2.4, angleDeg: 55,  advance: 1.6,
                   startup: 0.06, active: 0.08, recovery: 0.16, window: 0.34, knockback: 1.5 } },
        { close: { damage: 13, range: 1.9, angleDeg: 95,  advance: 0.6,
                   startup: 0.05, active: 0.08, recovery: 0.16, window: 0.34, knockback: 1.5 },
          far:   { damage: 17, range: 2.5, angleDeg: 60,  advance: 1.8,
                   startup: 0.07, active: 0.09, recovery: 0.18, window: 0.34, knockback: 1.8 } },
        { close: { damage: 22, range: 2.0, angleDeg: 120, advance: 0.4,
                   startup: 0.10, active: 0.12, recovery: 0.30, window: 0.14, knockback: 3.2 },
          far:   { damage: 28, range: 2.8, angleDeg: 70,  advance: 2.0,
                   startup: 0.12, active: 0.12, recovery: 0.32, window: 0.14, knockback: 3.5 } },
      ],
    },
    {
      name: 'Club',
      type: 'melee', class: 'melee', rarity: 'common',
      meleeThreshold: 2.9,
      tracerColor: 0x8a6a3c,
      muzzleLength: 0.8, muzzleGirth: 0.08,
      adsZoom: 0.82, adsPeekDistance: 2.6,
      combo: [
        { close: { damage: 14, range: 2.0, angleDeg: 95,  advance: 0.55,
                   startup: 0.06, active: 0.10, recovery: 0.20, window: 0.34, knockback: 2.2 },
          far:   { damage: 18, range: 2.6, angleDeg: 55,  advance: 1.7,
                   startup: 0.09, active: 0.10, recovery: 0.22, window: 0.34, knockback: 2.6 } },
        { close: { damage: 18, range: 2.1, angleDeg: 100, advance: 0.6,
                   startup: 0.07, active: 0.11, recovery: 0.22, window: 0.36, knockback: 2.8 },
          far:   { damage: 22, range: 2.8, angleDeg: 60,  advance: 1.9,
                   startup: 0.10, active: 0.11, recovery: 0.22, window: 0.36, knockback: 3.2 } },
        { close: { damage: 30, range: 2.3, angleDeg: 140, advance: 0.3,
                   startup: 0.13, active: 0.14, recovery: 0.38, window: 0.14, knockback: 5.0 },
          far:   { damage: 36, range: 3.0, angleDeg: 65,  advance: 2.2,
                   startup: 0.15, active: 0.13, recovery: 0.40, window: 0.14, knockback: 5.4 } },
      ],
    },
    {
      name: 'Baseball Bat',
      type: 'melee', class: 'melee', rarity: 'uncommon',
      meleeThreshold: 3.0,
      tracerColor: 0xb98a5c,
      muzzleLength: 0.95, muzzleGirth: 0.06,
      adsZoom: 0.8, adsPeekDistance: 2.7,
      combo: [
        { close: { damage: 16, range: 2.1, angleDeg: 95,  advance: 0.6,
                   startup: 0.06, active: 0.10, recovery: 0.20, window: 0.36, knockback: 2.5 },
          far:   { damage: 20, range: 2.9, angleDeg: 55,  advance: 1.9,
                   startup: 0.09, active: 0.11, recovery: 0.22, window: 0.36, knockback: 2.8 } },
        { close: { damage: 20, range: 2.2, angleDeg: 100, advance: 0.7,
                   startup: 0.08, active: 0.10, recovery: 0.22, window: 0.38, knockback: 3.0 },
          far:   { damage: 24, range: 3.1, angleDeg: 58,  advance: 2.1,
                   startup: 0.10, active: 0.11, recovery: 0.24, window: 0.38, knockback: 3.4 } },
        { close: { damage: 34, range: 2.5, angleDeg: 140, advance: 0.3,
                   startup: 0.13, active: 0.15, recovery: 0.40, window: 0.14, knockback: 5.5 },
          far:   { damage: 42, range: 3.4, angleDeg: 60,  advance: 2.5,
                   startup: 0.16, active: 0.14, recovery: 0.42, window: 0.14, knockback: 6.0 } },
      ],
    },
    {
      // Cursor distance from player picks a 'close' or 'far' variant per step.
      // Each step: startup (rooted) → active (lunges + deals damage once) →
      // recovery (rooted) → window (LMB chains to next step; timeout resets).
      name: 'katana',
      type: 'melee',
      class: 'melee',
      rarity: 'rare',
      meleeThreshold: 3.2,
      tracerColor: 0x9dd0ff,
      muzzleLength: 1.1,
      muzzleGirth: 0.06,
      adsZoom: 0.78,
      adsPeekDistance: 3.0,
      combo: [
        {
          close: { damage: 18, range: 2.2, angleDeg: 85, advance: 0.7,
                   startup: 0.05, active: 0.09, recovery: 0.18, window: 0.38,
                   knockback: 2.0 },
          far:   { damage: 24, range: 3.2, angleDeg: 50, advance: 2.2,
                   startup: 0.08, active: 0.10, recovery: 0.22, window: 0.40,
                   knockback: 2.5 },
        },
        {
          close: { damage: 22, range: 2.3, angleDeg: 100, advance: 0.9,
                   startup: 0.06, active: 0.10, recovery: 0.20, window: 0.40,
                   knockback: 2.5 },
          far:   { damage: 28, range: 3.4, angleDeg: 55, advance: 2.4,
                   startup: 0.10, active: 0.12, recovery: 0.24, window: 0.40,
                   knockback: 3.0 },
        },
        {
          close: { damage: 40, range: 2.7, angleDeg: 150, advance: 0.4,
                   startup: 0.14, active: 0.18, recovery: 0.45, window: 0.12,
                   knockback: 6.0,
                   shockwaveRadius: 3.6, shockwaveDamage: 28, shockwaveKnockback: 7 },
          far:   { damage: 48, range: 3.8, angleDeg: 60, advance: 2.8,
                   startup: 0.16, active: 0.14, recovery: 0.5, window: 0.12,
                   knockback: 6.0,
                   shockwaveRadius: 4.2, shockwaveDamage: 24, shockwaveKnockback: 6 },
        },
      ],
    },
    // --- Extended melee lineup ---
    {
      name: 'Brass Knuckles',
      type: 'melee', class: 'melee', rarity: 'common',
      meleeThreshold: 2.5,
      tracerColor: 0xc99030,
      muzzleLength: 0.3, muzzleGirth: 0.05,
      adsZoom: 0.82, adsPeekDistance: 2.2,
      combo: [
        { close: { damage: 8,  range: 1.5, angleDeg: 80, advance: 0.4,
                   startup: 0.03, active: 0.06, recovery: 0.10, window: 0.26, knockback: 1.0 },
          far:   { damage: 10, range: 1.9, angleDeg: 50, advance: 1.2,
                   startup: 0.04, active: 0.06, recovery: 0.12, window: 0.28, knockback: 1.2 } },
        { close: { damage: 11, range: 1.6, angleDeg: 85, advance: 0.45,
                   startup: 0.04, active: 0.07, recovery: 0.12, window: 0.26, knockback: 1.2 },
          far:   { damage: 14, range: 2.0, angleDeg: 55, advance: 1.3,
                   startup: 0.05, active: 0.07, recovery: 0.14, window: 0.28, knockback: 1.4 } },
        { close: { damage: 18, range: 1.8, angleDeg: 110, advance: 0.3,
                   startup: 0.07, active: 0.10, recovery: 0.24, window: 0.12, knockback: 2.4 },
          far:   { damage: 22, range: 2.4, angleDeg: 60, advance: 1.5,
                   startup: 0.09, active: 0.10, recovery: 0.26, window: 0.12, knockback: 2.8 } },
      ],
    },
    {
      name: 'Crowbar',
      type: 'melee', class: 'melee', rarity: 'common',
      meleeThreshold: 2.9,
      tracerColor: 0x7a4a30,
      muzzleLength: 0.9, muzzleGirth: 0.05,
      adsZoom: 0.82, adsPeekDistance: 2.6,
      combo: [
        { close: { damage: 12, range: 2.0, angleDeg: 90, advance: 0.55,
                   startup: 0.05, active: 0.09, recovery: 0.18, window: 0.32, knockback: 1.8 },
          far:   { damage: 16, range: 2.7, angleDeg: 55, advance: 1.8,
                   startup: 0.08, active: 0.10, recovery: 0.22, window: 0.34, knockback: 2.2 } },
        { close: { damage: 15, range: 2.1, angleDeg: 95, advance: 0.6,
                   startup: 0.06, active: 0.10, recovery: 0.20, window: 0.34, knockback: 2.2 },
          far:   { damage: 19, range: 2.8, angleDeg: 60, advance: 2.0,
                   startup: 0.09, active: 0.10, recovery: 0.22, window: 0.34, knockback: 2.6 } },
        { close: { damage: 26, range: 2.3, angleDeg: 130, advance: 0.35,
                   startup: 0.12, active: 0.13, recovery: 0.36, window: 0.14, knockback: 4.4 },
          far:   { damage: 32, range: 3.0, angleDeg: 65, advance: 2.2,
                   startup: 0.14, active: 0.12, recovery: 0.38, window: 0.14, knockback: 4.8 } },
      ],
    },
    {
      name: 'Kukri',
      type: 'melee', class: 'melee', rarity: 'uncommon',
      meleeThreshold: 2.9,
      tracerColor: 0xb8b0a0,
      muzzleLength: 0.7, muzzleGirth: 0.05,
      adsZoom: 0.8, adsPeekDistance: 2.6,
      combo: [
        { close: { damage: 14, range: 2.0, angleDeg: 95, advance: 0.6,
                   startup: 0.04, active: 0.08, recovery: 0.14, window: 0.32, knockback: 1.4 },
          far:   { damage: 18, range: 2.8, angleDeg: 55, advance: 1.9,
                   startup: 0.06, active: 0.09, recovery: 0.18, window: 0.34, knockback: 1.6 } },
        { close: { damage: 18, range: 2.1, angleDeg: 100, advance: 0.65,
                   startup: 0.05, active: 0.08, recovery: 0.16, window: 0.32, knockback: 1.6 },
          far:   { damage: 22, range: 2.9, angleDeg: 58, advance: 2.0,
                   startup: 0.07, active: 0.09, recovery: 0.18, window: 0.34, knockback: 1.8 } },
        { close: { damage: 28, range: 2.3, angleDeg: 125, advance: 0.4,
                   startup: 0.10, active: 0.12, recovery: 0.30, window: 0.14, knockback: 3.2 },
          far:   { damage: 34, range: 3.0, angleDeg: 65, advance: 2.3,
                   startup: 0.12, active: 0.12, recovery: 0.32, window: 0.14, knockback: 3.6 } },
      ],
    },
    {
      name: 'Tomahawk',
      type: 'melee', class: 'melee', rarity: 'uncommon',
      meleeThreshold: 3.0,
      tracerColor: 0x8a5a2a,
      muzzleLength: 0.85, muzzleGirth: 0.08,
      adsZoom: 0.8, adsPeekDistance: 2.7,
      combo: [
        { close: { damage: 18, range: 2.1, angleDeg: 90, advance: 0.55,
                   startup: 0.06, active: 0.10, recovery: 0.20, window: 0.34, knockback: 2.0 },
          far:   { damage: 22, range: 2.8, angleDeg: 55, advance: 1.9,
                   startup: 0.09, active: 0.11, recovery: 0.22, window: 0.36, knockback: 2.4 } },
        { close: { damage: 22, range: 2.2, angleDeg: 100, advance: 0.6,
                   startup: 0.07, active: 0.11, recovery: 0.22, window: 0.36, knockback: 2.4 },
          far:   { damage: 26, range: 2.9, angleDeg: 58, advance: 2.0,
                   startup: 0.10, active: 0.11, recovery: 0.22, window: 0.36, knockback: 2.8 } },
        { close: { damage: 34, range: 2.5, angleDeg: 130, advance: 0.35,
                   startup: 0.13, active: 0.14, recovery: 0.40, window: 0.14, knockback: 5.0 },
          far:   { damage: 40, range: 3.1, angleDeg: 62, advance: 2.4,
                   startup: 0.15, active: 0.13, recovery: 0.42, window: 0.14, knockback: 5.4 } },
      ],
    },
    {
      name: 'Fire Axe',
      type: 'melee', class: 'melee', rarity: 'uncommon',
      meleeThreshold: 3.1,
      tracerColor: 0xb04030,
      muzzleLength: 1.0, muzzleGirth: 0.08,
      adsZoom: 0.78, adsPeekDistance: 2.7,
      combo: [
        { close: { damage: 22, range: 2.3, angleDeg: 100, advance: 0.55,
                   startup: 0.08, active: 0.12, recovery: 0.24, window: 0.36, knockback: 2.6 },
          far:   { damage: 28, range: 3.0, angleDeg: 58, advance: 2.1,
                   startup: 0.11, active: 0.13, recovery: 0.26, window: 0.38, knockback: 3.0 } },
        { close: { damage: 27, range: 2.4, angleDeg: 105, advance: 0.6,
                   startup: 0.09, active: 0.13, recovery: 0.26, window: 0.38, knockback: 3.0 },
          far:   { damage: 33, range: 3.1, angleDeg: 60, advance: 2.3,
                   startup: 0.12, active: 0.13, recovery: 0.28, window: 0.38, knockback: 3.4 } },
        { close: { damage: 42, range: 2.6, angleDeg: 140, advance: 0.3,
                   startup: 0.15, active: 0.16, recovery: 0.44, window: 0.14, knockback: 6.0 },
          far:   { damage: 50, range: 3.3, angleDeg: 62, advance: 2.6,
                   startup: 0.18, active: 0.15, recovery: 0.46, window: 0.14, knockback: 6.4 } },
      ],
    },
    {
      name: 'Sledgehammer',
      type: 'melee', class: 'melee', rarity: 'rare',
      meleeThreshold: 3.3,
      tracerColor: 0x505868,
      muzzleLength: 1.1, muzzleGirth: 0.12,
      adsZoom: 0.76, adsPeekDistance: 2.8,
      combo: [
        { close: { damage: 28, range: 2.3, angleDeg: 100, advance: 0.5,
                   startup: 0.10, active: 0.14, recovery: 0.28, window: 0.36, knockback: 3.6 },
          far:   { damage: 36, range: 3.1, angleDeg: 55, advance: 2.1,
                   startup: 0.14, active: 0.15, recovery: 0.32, window: 0.38, knockback: 4.2 } },
        { close: { damage: 34, range: 2.4, angleDeg: 105, advance: 0.55,
                   startup: 0.11, active: 0.15, recovery: 0.30, window: 0.38, knockback: 4.2 },
          far:   { damage: 42, range: 3.2, angleDeg: 58, advance: 2.3,
                   startup: 0.15, active: 0.15, recovery: 0.32, window: 0.38, knockback: 4.8 } },
        { close: { damage: 56, range: 2.7, angleDeg: 150, advance: 0.3,
                   startup: 0.18, active: 0.20, recovery: 0.50, window: 0.12, knockback: 7.5,
                   shockwaveRadius: 3.2, shockwaveDamage: 22, shockwaveKnockback: 5 },
          far:   { damage: 64, range: 3.5, angleDeg: 62, advance: 2.7,
                   startup: 0.20, active: 0.16, recovery: 0.52, window: 0.12, knockback: 8.0,
                   shockwaveRadius: 3.8, shockwaveDamage: 20, shockwaveKnockback: 5 } },
      ],
    },
    {
      name: 'Chainsaw',
      type: 'melee', class: 'melee', rarity: 'epic',
      meleeThreshold: 3.0,
      tracerColor: 0xd08020,
      muzzleLength: 0.95, muzzleGirth: 0.14,
      adsZoom: 0.8, adsPeekDistance: 2.6,
      // Chainsaw: stupid-high DPS, loud. Shorter swings trade knockback
      // for faster follow-ups; the 3rd step stays committed but without a
      // shockwave (its damage is already extreme).
      combo: [
        { close: { damage: 24, range: 1.9, angleDeg: 85, advance: 0.5,
                   startup: 0.05, active: 0.09, recovery: 0.16, window: 0.26, knockback: 1.2 },
          far:   { damage: 30, range: 2.6, angleDeg: 50, advance: 1.8,
                   startup: 0.07, active: 0.10, recovery: 0.18, window: 0.28, knockback: 1.4 } },
        { close: { damage: 30, range: 2.0, angleDeg: 90, advance: 0.55,
                   startup: 0.06, active: 0.09, recovery: 0.18, window: 0.28, knockback: 1.4 },
          far:   { damage: 36, range: 2.7, angleDeg: 52, advance: 1.9,
                   startup: 0.08, active: 0.10, recovery: 0.18, window: 0.28, knockback: 1.6 } },
        { close: { damage: 48, range: 2.1, angleDeg: 110, advance: 0.4,
                   startup: 0.11, active: 0.13, recovery: 0.30, window: 0.12, knockback: 2.2 },
          far:   { damage: 56, range: 2.8, angleDeg: 60, advance: 2.0,
                   startup: 0.13, active: 0.13, recovery: 0.32, window: 0.12, knockback: 2.6 } },
      ],
    },
  ],
};
